### ISSUE TITLE
Allison Bierschenk - rendering data using map

### ISSUE THREAD

**Issue by allisonbierschenk** [allisonbierschenk/Work_it_out#1]
# PROJECT ISSUE TICKET
```
import { baseURL, config } from "../services";
import { useState, useEffect } from "react";
import axios from "axios";

function Legs(props) {
  const workout = props.workouts.map((workout) => workout.fields);
  console.log("workout const", workout);
  const workoutCategory = workout.map(
    (workoutCategory) => workoutCategory.category
  );
  console.log(workoutCategory[1]);

  return (
    <div>
      <h2>Workouts</h2>
      <h3>{workoutCategory[0] === "legs" ? <p>{workout}</p> : null}</h3>
    </div>
  );
}

export default Legs;
```
## Unexpected Behavior

> I can't figure out what I need to do in order to render the specific keys and values of an object if the category = legs. 

## Expected Behavior

> What I am trying to do is say in the ternary if the workoutCategory === legs then render the rest of the objects keys and values. Right now, I can only hard code the indicy but I need it to map through the array and say if it === legs render the rest of the object, if not do nothing.
So there are two issues: 1. the map isn't working quite right and 2. the ternary isn't rendering object key and values

I feel like I am using map a lot already and I am sure there is a better way

## Reproduce the Error

> Describe the steps we can take to reproduce the error, i.e.:

```md
1. Clone this repo.
2. Run `npm start`.
3. Navigate to the legs page.
4. you can see what I am getting data in the console but when I try to use it it is throwing the error
```

## Documentation

> Include the exact error message, and if helpful, any supplemental documentation, such as screen captures.

```
react-dom.development.js:13231 Uncaught Error: Objects are not valid as a React child (found: object with keys {weight, category, workout, reps, sets, date}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13231)
    at createChild (react-dom.development.js:13469)
    at reconcileChildrenArray (react-dom.development.js:13719)
    at reconcileChildFibers (react-dom.development.js:14125)
    at reconcileChildren (react-dom.development.js:16997)
    at updateHostComponent (react-dom.development.js:17632)
    at beginWork (react-dom.development.js:19080)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at flushSync (react-dom.development.js:22467)
    at Object.scheduleRefresh (react-dom.development.js:24429)
    at react-refresh-runtime.development.js:304
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js:293)
    at RefreshUtils.js:62
throwOnInvalidObjectType @ react-dom.development.js:13231
createChild @ react-dom.development.js:13469
reconcileChildrenArray @ react-dom.development.js:13719
reconcileChildFibers @ react-dom.development.js:14125
reconcileChildren @ react-dom.development.js:16997
updateHostComponent @ react-dom.development.js:17632
beginWork @ react-dom.development.js:19080
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushSync @ react-dom.development.js:22467
scheduleRefresh @ react-dom.development.js:24429
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:62
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:60
(anonymous) @ Legs.jsx:22
./src/components/Legs.jsx @ Legs.jsx:22
__webpack_require__ @ bootstrap:856
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
(anonymous) @ bootstrap:386
Promise.then (async)
hotUpdateDownloaded @ bootstrap:385
hotAddUpdateChunk @ bootstrap:361
webpackHotUpdateCallback @ bootstrap:57
(anonymous) @ main.47eb993e4417597212fe.hot-update.js:1
index.js:1 The above error occurred in the <p> component:

    at p
    at h3
    at div
    at Legs (http://localhost:3000/main.47eb993e4417597212fe.hot-update.js:29:25)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:36387:29)
    at div
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:182:89)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:36022:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:35642:35)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushSync @ react-dom.development.js:22467
scheduleRefresh @ react-dom.development.js:24429
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:62
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:60
(anonymous) @ Legs.jsx:22
./src/components/Legs.jsx @ Legs.jsx:22
__webpack_require__ @ bootstrap:856
hotApplyInternal @ bootstrap:749
hotApply @ bootstrap:411
(anonymous) @ bootstrap:386
Promise.then (async)
hotUpdateDownloaded @ bootstrap:385
hotAddUpdateChunk @ bootstrap:361
webpackHotUpdateCallback @ bootstrap:57
(anonymous) @ main.47eb993e4417597212fe.hot-update.js:1
react-dom.development.js:13231 Uncaught Error: Objects are not valid as a React child (found: object with keys {weight, category, workout, reps, sets, date}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:13231)
    at createChild (react-dom.development.js:13469)
    at reconcileChildrenArray (react-dom.development.js:13719)
    at reconcileChildFibers (react-dom.development.js:14125)
    at reconcileChildren (react-dom.development.js:16997)
    at updateHostComponent (react-dom.development.js:17632)
    at beginWork (react-dom.development.js:19080)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at flushSync (react-dom.development.js:22467)
    at Object.scheduleRefresh (react-dom.development.js:24429)
    at react-refresh-runtime.development.js:304
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js:293)
    at RefreshUtils.js:62
```

## Attempted Resolution

> I have looked at old repos and documentation on conditional rendering

```md
1.https://reactjs.org/docs/conditional-rendering.html
2.https://git.generalassemb.ly/sei-nyc-sapphire/robotanist/tree/main/src
```

**Comment by smapets** [comment]
```
function Legs(props) {
  const legWorkout = props.workouts.filter((workout) => workout.fields.category==="legs");
  const  listOfLegWorkout=legWorkout.map(workout=>{
    return(
    <div>
    <p>id:{workout.id}<br/>workout:{workout.fields.workout}<br/>reps:{workout.fields.reps}<br/>sets:{workout.fields.sets}</p>
    </div>
  )

})

  return (
    <div>
      <h2>Workouts</h2>
      {listOfLegWorkout}
    </div>
  );
}
```

**Comment by smapets** [comment]
I would use filter in this case.
